import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import Cursor from "@/components/Cursor";
import { Toaster } from "react-hot-toast";
import BannerMessage from "@/components/BannerMessage";
const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "#V0ID",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSansArabic.className} antialiased`}>
        {/* Global Cursor */}
        <Cursor />

        {/* Global Toaster */}
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        {children}
        <BannerMessage />
      </body>
    </html>
  );
}